
package com.rose.mps.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.rose.mps.domain.hotel.publicservice.InvokeResult;
import com.rose.mps.domain.hotel.publicservice.InvokeResultArrayOfFloorResponse;
import com.rose.mps.domain.hotel.publicservice.InvokeResultArrayOfHotelSearchResponse;
import com.rose.mps.domain.hotel.publicservice.InvokeResultArrayOfHotelServiceTag;
import com.rose.mps.domain.hotel.publicservice.InvokeResultArrayOfOwnerConfig;
import com.rose.mps.domain.hotel.publicservice.InvokeResultArrayOfRoom;
import com.rose.mps.domain.hotel.publicservice.InvokeResultArrayOfRoomType;
import com.rose.mps.domain.hotel.publicservice.InvokeResultBoolean;
import com.rose.mps.domain.hotel.publicservice.InvokeResultInt;
import com.rose.mps.domain.hotel.publicservice.InvokeResultPagedResultOfRoomRemarkResponsepM6ZO2Ns;
import com.rose.mps.domain.hotel.publicservice.model.ArrayOfRoomType;
import com.rose.mps.domain.hotel.publicservice.model.HotelLocationUpdateRequest;
import com.rose.mps.domain.hotel.publicservice.model.HotelSearchRequest;
import com.rose.mps.domain.hotel.publicservice.model.RoomRemarkAddRequest;
import com.rose.mps.domain.hotel.publicservice.model.RoomRemarkSearchRequest;
import com.rose.mps.domain.hotel.publicservice.model.SearchAvailiableRooms;
import com.rose.mps.domain.hotel.serialization.array.ArrayOflong;
import com.rose.mps.domain.hotel.serialization.array.ArrayOfstring;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IHotelService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.rose.mps.domain.hotel.publicservice.model.ObjectFactory.class,
    com.rose.mps.domain.hotel.serialization.array.ObjectFactory.class,
    com.rose.mps.domain.hotel.serialization.array.ObjectFactory.class,
    com.rose.mps.domain.hotel.publicservice.ObjectFactory.class,
    com.rose.mps.domain.hotel.tempuri.ObjectFactory.class
})
public interface IHotelService {


    /**
     * 
     * @param unixExpireTimestamp
     * @param signature
     * @return
     *     returns com.rose.domain.publicservice.InvokeResultArrayOfOwnerConfig
     */
    @WebMethod(operationName = "GetHotelBrands", action = "http://tempuri.org/IHotelService/GetHotelBrands")
    @WebResult(name = "GetHotelBrandsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetHotelBrands", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetHotelBrands")
    @ResponseWrapper(localName = "GetHotelBrandsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetHotelBrandsResponse")
    public InvokeResultArrayOfOwnerConfig getHotelBrands(
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

    /**
     * 
     * @param unixExpireTimestamp
     * @param signature
     * @return
     *     returns com.rose.domain.publicservice.InvokeResultArrayOfRoomType
     */
    @WebMethod(operationName = "GetRoomTypes", action = "http://tempuri.org/IHotelService/GetRoomTypes")
    @WebResult(name = "GetRoomTypesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRoomTypes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRoomTypes")
    @ResponseWrapper(localName = "GetRoomTypesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRoomTypesResponse")
    public InvokeResultArrayOfRoomType getRoomTypes(
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

    /**
     * 
     * @param unixExpireTimestamp
     * @param hotelId
     * @param signature
     * @return
     *     returns com.rose.domain.publicservice.InvokeResultArrayOfRoomType
     */
    @WebMethod(operationName = "GetHotelRoomTypes", action = "http://tempuri.org/IHotelService/GetHotelRoomTypes")
    @WebResult(name = "GetHotelRoomTypesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetHotelRoomTypes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetHotelRoomTypes")
    @ResponseWrapper(localName = "GetHotelRoomTypesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetHotelRoomTypesResponse")
    public InvokeResultArrayOfRoomType getHotelRoomTypes(
        @WebParam(name = "hotelId", targetNamespace = "http://tempuri.org/")
        Long hotelId,
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

    /**
     * 
     * @param unixExpireTimestamp
     * @param signature
     * @return
     *     returns com.rose.domain.publicservice.InvokeResultArrayOfHotelServiceTag
     */
    @WebMethod(operationName = "GetServiceTags", action = "http://tempuri.org/IHotelService/GetServiceTags")
    @WebResult(name = "GetServiceTagsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetServiceTags", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetServiceTags")
    @ResponseWrapper(localName = "GetServiceTagsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetServiceTagsResponse")
    public InvokeResultArrayOfHotelServiceTag getServiceTags(
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

    /**
     * 
     * @param unixExpireTimestamp
     * @param pageSize
     * @param signature
     * @param pageIndex
     * @return
     *     returns com.rose.domain.publicservice.InvokeResultArrayOfHotelSearchResponse
     */
    @WebMethod(operationName = "GetAllHotels", action = "http://tempuri.org/IHotelService/GetAllHotels")
    @WebResult(name = "GetAllHotelsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAllHotels", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllHotels")
    @ResponseWrapper(localName = "GetAllHotelsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllHotelsResponse")
    public InvokeResultArrayOfHotelSearchResponse getAllHotels(
        @WebParam(name = "pageIndex", targetNamespace = "http://tempuri.org/")
        Integer pageIndex,
        @WebParam(name = "pageSize", targetNamespace = "http://tempuri.org/")
        Integer pageSize,
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

    /**
     * 
     * @param unixExpireTimestamp
     * @param searchRequest
     * @param signature
     * @return
     *     returns com.rose.domain.publicservice.InvokeResultArrayOfHotelSearchResponse
     */
    @WebMethod(operationName = "Search", action = "http://tempuri.org/IHotelService/Search")
    @WebResult(name = "SearchResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Search", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Search")
    @ResponseWrapper(localName = "SearchResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchResponse")
    public InvokeResultArrayOfHotelSearchResponse search(
        @WebParam(name = "searchRequest", targetNamespace = "http://tempuri.org/")
        HotelSearchRequest searchRequest,
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

    /**
     * 
     * @param orgId
     * @param unixExpireTimestamp
     * @param signature
     * @return
     *     returns com.rose.domain.publicservice.InvokeResultArrayOfFloorResponse
     */
    @WebMethod(operationName = "GetFloor", action = "http://tempuri.org/IHotelService/GetFloor")
    @WebResult(name = "GetFloorResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetFloor", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetFloor")
    @ResponseWrapper(localName = "GetFloorResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetFloorResponse")
    public InvokeResultArrayOfFloorResponse getFloor(
        @WebParam(name = "orgId", targetNamespace = "http://tempuri.org/")
        Long orgId,
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

    /**
     * 
     * @param hallId
     * @param utcTimestamp
     * @param floorId
     * @param unixExpireTimestamp
     * @param pageSize
     * @param roomStatus
     * @param hotelId
     * @param signature
     * @param pageIndex
     * @return
     *     returns com.rose.domain.publicservice.InvokeResultArrayOfRoom
     */
    @WebMethod(operationName = "GetRooms", action = "http://tempuri.org/IHotelService/GetRooms")
    @WebResult(name = "GetRoomsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRooms", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRooms")
    @ResponseWrapper(localName = "GetRoomsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRoomsResponse")
    public InvokeResultArrayOfRoom getRooms(
        @WebParam(name = "utcTimestamp", targetNamespace = "http://tempuri.org/")
        Long utcTimestamp,
        @WebParam(name = "hotelId", targetNamespace = "http://tempuri.org/")
        Long hotelId,
        @WebParam(name = "pageIndex", targetNamespace = "http://tempuri.org/")
        Integer pageIndex,
        @WebParam(name = "pageSize", targetNamespace = "http://tempuri.org/")
        Integer pageSize,
        @WebParam(name = "roomStatus", targetNamespace = "http://tempuri.org/")
        String roomStatus,
        @WebParam(name = "hallId", targetNamespace = "http://tempuri.org/")
        Long hallId,
        @WebParam(name = "floorId", targetNamespace = "http://tempuri.org/")
        Long floorId,
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

    /**
     * 
     * @param searchAvailiableRoomModel
     * @param unixExpireTimestamp
     * @param signature
     * @return
     *     returns com.rose.domain.publicservice.InvokeResultArrayOfRoom
     */
    @WebMethod(operationName = "SearchAvailiableRooms", action = "http://tempuri.org/IHotelService/SearchAvailiableRooms")
    @WebResult(name = "SearchAvailiableRoomsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SearchAvailiableRooms", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchAvailiableRooms")
    @ResponseWrapper(localName = "SearchAvailiableRoomsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchAvailiableRoomsResponse")
    public InvokeResultArrayOfRoom searchAvailiableRooms(
        @WebParam(name = "searchAvailiableRoomModel", targetNamespace = "http://tempuri.org/")
        SearchAvailiableRooms searchAvailiableRoomModel,
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

    /**
     * 
     * @param unixExpireTimestamp
     * @param searchRequest
     * @param signature
     * @return
     *     returns com.rose.domain.publicservice.InvokeResultInt
     */
    @WebMethod(operationName = "GetSearchResultCount", action = "http://tempuri.org/IHotelService/GetSearchResultCount")
    @WebResult(name = "GetSearchResultCountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSearchResultCount", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSearchResultCount")
    @ResponseWrapper(localName = "GetSearchResultCountResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSearchResultCountResponse")
    public InvokeResultInt getSearchResultCount(
        @WebParam(name = "searchRequest", targetNamespace = "http://tempuri.org/")
        HotelSearchRequest searchRequest,
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

    /**
     * 
     * @param hallId
     * @param utcTimestamp
     * @param floorId
     * @param unixExpireTimestamp
     * @param roomStatus
     * @param hotelId
     * @param signature
     * @return
     *     returns com.rose.domain.publicservice.InvokeResultInt
     */
    @WebMethod(operationName = "GetRoomsCount", action = "http://tempuri.org/IHotelService/GetRoomsCount")
    @WebResult(name = "GetRoomsCountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRoomsCount", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRoomsCount")
    @ResponseWrapper(localName = "GetRoomsCountResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRoomsCountResponse")
    public InvokeResultInt getRoomsCount(
        @WebParam(name = "utcTimestamp", targetNamespace = "http://tempuri.org/")
        Long utcTimestamp,
        @WebParam(name = "hotelId", targetNamespace = "http://tempuri.org/")
        Long hotelId,
        @WebParam(name = "roomStatus", targetNamespace = "http://tempuri.org/")
        String roomStatus,
        @WebParam(name = "hallId", targetNamespace = "http://tempuri.org/")
        Long hallId,
        @WebParam(name = "floorId", targetNamespace = "http://tempuri.org/")
        Long floorId,
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

    /**
     * 
     * @param unixExpireTimestamp
     * @param signature
     * @param newRoomTypes
     * @return
     *     returns com.rose.domain.publicservice.InvokeResult
     */
    @WebMethod(operationName = "AddRoomTypes", action = "http://tempuri.org/IHotelService/AddRoomTypes")
    @WebResult(name = "AddRoomTypesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddRoomTypes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddRoomTypes")
    @ResponseWrapper(localName = "AddRoomTypesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddRoomTypesResponse")
    public InvokeResult addRoomTypes(
        @WebParam(name = "newRoomTypes", targetNamespace = "http://tempuri.org/")
        ArrayOfRoomType newRoomTypes,
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

    /**
     * 
     * @param unixExpireTimestamp
     * @param hotelIds
     * @param signature
     * @return
     *     returns com.rose.domain.publicservice.InvokeResultArrayOfHotelSearchResponse
     */
    @WebMethod(operationName = "GetHotelsByHotelIds", action = "http://tempuri.org/IHotelService/GetHotelsByHotelIds")
    @WebResult(name = "GetHotelsByHotelIdsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetHotelsByHotelIds", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetHotelsByHotelIds")
    @ResponseWrapper(localName = "GetHotelsByHotelIdsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetHotelsByHotelIdsResponse")
    public InvokeResultArrayOfHotelSearchResponse getHotelsByHotelIds(
        @WebParam(name = "hotelIds", targetNamespace = "http://tempuri.org/")
        ArrayOflong hotelIds,
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

    /**
     * 
     * @param unixExpireTimestamp
     * @param hotelNos
     * @param signature
     * @return
     *     returns com.rose.domain.publicservice.InvokeResultArrayOfHotelSearchResponse
     */
    @WebMethod(operationName = "GetHotelsByHotelNos", action = "http://tempuri.org/IHotelService/GetHotelsByHotelNos")
    @WebResult(name = "GetHotelsByHotelNosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetHotelsByHotelNos", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetHotelsByHotelNos")
    @ResponseWrapper(localName = "GetHotelsByHotelNosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetHotelsByHotelNosResponse")
    public InvokeResultArrayOfHotelSearchResponse getHotelsByHotelNos(
        @WebParam(name = "hotelNos", targetNamespace = "http://tempuri.org/")
        ArrayOfstring hotelNos,
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

    /**
     * 
     * @param unixExpireTimestamp
     * @param roomRemarkSearchRequest
     * @param signature
     * @return
     *     returns com.rose.domain.publicservice.InvokeResultPagedResultOfRoomRemarkResponsepM6ZO2Ns
     */
    @WebMethod(operationName = "SearchRoomRemark", action = "http://tempuri.org/IHotelService/SearchRoomRemark")
    @WebResult(name = "SearchRoomRemarkResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SearchRoomRemark", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchRoomRemark")
    @ResponseWrapper(localName = "SearchRoomRemarkResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchRoomRemarkResponse")
    public InvokeResultPagedResultOfRoomRemarkResponsepM6ZO2Ns searchRoomRemark(
        @WebParam(name = "roomRemarkSearchRequest", targetNamespace = "http://tempuri.org/")
        RoomRemarkSearchRequest roomRemarkSearchRequest,
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

    /**
     * 
     * @param unixExpireTimestamp
     * @param roomRemarkAddRequest
     * @param signature
     * @return
     *     returns com.rose.domain.publicservice.InvokeResultBoolean
     */
    @WebMethod(operationName = "AddRoomRemark", action = "http://tempuri.org/IHotelService/AddRoomRemark")
    @WebResult(name = "AddRoomRemarkResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddRoomRemark", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddRoomRemark")
    @ResponseWrapper(localName = "AddRoomRemarkResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddRoomRemarkResponse")
    public InvokeResultBoolean addRoomRemark(
        @WebParam(name = "roomRemarkAddRequest", targetNamespace = "http://tempuri.org/")
        RoomRemarkAddRequest roomRemarkAddRequest,
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

    /**
     * 
     * @param unixExpireTimestamp
     * @param hotelLocationUpdateRequest
     * @param signature
     * @return
     *     returns com.rose.domain.publicservice.InvokeResultBoolean
     */
    @WebMethod(operationName = "UpdateHotelLocationId", action = "http://tempuri.org/IHotelService/UpdateHotelLocationId")
    @WebResult(name = "UpdateHotelLocationIdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateHotelLocationId", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateHotelLocationId")
    @ResponseWrapper(localName = "UpdateHotelLocationIdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateHotelLocationIdResponse")
    public InvokeResultBoolean updateHotelLocationId(
        @WebParam(name = "hotelLocationUpdateRequest", targetNamespace = "http://tempuri.org/")
        HotelLocationUpdateRequest hotelLocationUpdateRequest,
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

}
