
package com.rose.mps.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.rose.mps.domain.order.publicservice.InvokeResultArrayOfCheckinGuestResponse;
import com.rose.mps.domain.order.publicservice.InvokeResultArrayOfCheckinNetDoorResponse;
import com.rose.mps.domain.order.publicservice.InvokeResultArrayOfCheckinResponse;
import com.rose.mps.domain.order.publicservice.InvokeResultArrayOfCheckoutResponse;
import com.rose.mps.domain.order.publicservice.InvokeResultArrayOfOccupationResponse;
import com.rose.mps.domain.order.publicservice.InvokeResultArrayOfPromotionPolicyResponse;
import com.rose.mps.domain.order.publicservice.InvokeResultBoolean;
import com.rose.mps.domain.order.publicservice.InvokeResultCheckinResponse;
import com.rose.mps.domain.order.publicservice.InvokeResultOrderAddResponse;
import com.rose.mps.domain.order.publicservice.InvokeResultOrderResponse;
import com.rose.mps.domain.order.publicservice.InvokeResultPageModelOfOrderResponsepM6ZO2Ns;
import com.rose.mps.domain.order.publicservice.model.ChangeStayRequest;
import com.rose.mps.domain.order.publicservice.model.CheckGuestIdCardRequest;
import com.rose.mps.domain.order.publicservice.model.CheckinGuestRequest;
import com.rose.mps.domain.order.publicservice.model.CheckinNetDoorOpenRequest;
import com.rose.mps.domain.order.publicservice.model.CheckinNetDoorRequest;
import com.rose.mps.domain.order.publicservice.model.CheckinRequest;
import com.rose.mps.domain.order.publicservice.model.CheckinSearchRequest;
import com.rose.mps.domain.order.publicservice.model.CheckoutRequest;
import com.rose.mps.domain.order.publicservice.model.GetOrdersByMemberIdRequest;
import com.rose.mps.domain.order.publicservice.model.OccupationSearchRequest;
import com.rose.mps.domain.order.publicservice.model.OrderAddRequest;
import com.rose.mps.domain.order.publicservice.model.OrderCancelRequest;
import com.rose.mps.domain.order.publicservice.model.SearchRequest;
import com.rose.mps.domain.order.tempuri.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IOrderService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
	com.rose.mps.domain.order.dal.entity.ObjectFactory.class,
	com.rose.mps.domain.order.serialization.ObjectFactory.class,
	com.rose.mps.domain.order.tempuri.ObjectFactory.class,
    com.rose.mps.domain.order.publicservice.model.ObjectFactory.class,
    com.rose.mps.domain.order.serialization.array.ObjectFactory.class,
    com.rose.mps.domain.order.publicservice.ObjectFactory.class,
    com.rose.mps.domain.order.mpsinterface.ObjectFactory.class
})
public interface IOrderService {


    /**
     * 
     * @param unixExpireTimestamp
     * @param orderAddRequest
     * @param signature
     * @return
     *     returns com.rose.mps.domain.order.publicservice.InvokeResultOrderAddResponse
     */
    @WebMethod(operationName = "AddOrder", action = "http://tempuri.org/IOrderService/AddOrder")
    @WebResult(name = "AddOrderResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddOrder", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddOrder")
    @ResponseWrapper(localName = "AddOrderResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddOrderResponse")
    public InvokeResultOrderAddResponse addOrder(
        @WebParam(name = "orderAddRequest", targetNamespace = "http://tempuri.org/")
        OrderAddRequest orderAddRequest,
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

    /**
     * 
     * @param unixExpireTimestamp
     * @param hotelId
     * @param signature
     * @param orderId
     * @return
     *     returns com.rose.mps.domain.order.publicservice.InvokeResultOrderResponse
     */
    @WebMethod(operationName = "GetOrder", action = "http://tempuri.org/IOrderService/GetOrder")
    @WebResult(name = "GetOrderResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetOrder", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOrder")
    @ResponseWrapper(localName = "GetOrderResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOrderResponse")
    public InvokeResultOrderResponse getOrder(
        @WebParam(name = "orderId", targetNamespace = "http://tempuri.org/")
        Long orderId,
        @WebParam(name = "hotelId", targetNamespace = "http://tempuri.org/")
        Long hotelId,
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

    /**
     * 
     * @param orderCancelRequest
     * @param unixExpireTimestamp
     * @param signature
     * @return
     *     returns com.rose.mps.domain.order.publicservice.InvokeResultBoolean
     */
    @WebMethod(operationName = "CancelOrder", action = "http://tempuri.org/IOrderService/CancelOrder")
    @WebResult(name = "CancelOrderResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelOrder", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelOrder")
    @ResponseWrapper(localName = "CancelOrderResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelOrderResponse")
    public InvokeResultBoolean cancelOrder(
        @WebParam(name = "orderCancelRequest", targetNamespace = "http://tempuri.org/")
        OrderCancelRequest orderCancelRequest,
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

    /**
     * 
     * @param unixExpireTimestamp
     * @param searchRequest
     * @param signature
     * @return
     *     returns com.rose.mps.domain.order.publicservice.InvokeResultPageModelOfOrderResponsepM6ZO2Ns
     */
    @WebMethod(operationName = "Search", action = "http://tempuri.org/IOrderService/Search")
    @WebResult(name = "SearchResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Search", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Search")
    @ResponseWrapper(localName = "SearchResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchResponse")
    public InvokeResultPageModelOfOrderResponsepM6ZO2Ns search(
        @WebParam(name = "searchRequest", targetNamespace = "http://tempuri.org/")
        SearchRequest searchRequest,
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

    /**
     * 
     * @param ordersByMemberIdRequest
     * @param unixExpireTimestamp
     * @param signature
     * @return
     *     returns com.rose.mps.domain.order.publicservice.InvokeResultPageModelOfOrderResponsepM6ZO2Ns
     */
    @WebMethod(operationName = "GetOrdersByMemberId", action = "http://tempuri.org/IOrderService/GetOrdersByMemberId")
    @WebResult(name = "GetOrdersByMemberIdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetOrdersByMemberId", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOrdersByMemberId")
    @ResponseWrapper(localName = "GetOrdersByMemberIdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOrdersByMemberIdResponse")
    public InvokeResultPageModelOfOrderResponsepM6ZO2Ns getOrdersByMemberId(
        @WebParam(name = "ordersByMemberIdRequest", targetNamespace = "http://tempuri.org/")
        GetOrdersByMemberIdRequest ordersByMemberIdRequest,
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

    /**
     * 
     * @param unixExpireTimestamp
     * @param orderAddRequest
     * @param signature
     * @return
     *     returns com.rose.mps.domain.order.publicservice.InvokeResultArrayOfPromotionPolicyResponse
     */
    @WebMethod(operationName = "GetPromotionPolicyResponse", action = "http://tempuri.org/IOrderService/GetPromotionPolicyResponse")
    @WebResult(name = "GetPromotionPolicyResponseResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPromotionPolicyResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPromotionPolicyResponse")
    @ResponseWrapper(localName = "GetPromotionPolicyResponseResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPromotionPolicyResponseResponse")
    public InvokeResultArrayOfPromotionPolicyResponse getPromotionPolicyResponse(
        @WebParam(name = "orderAddRequest", targetNamespace = "http://tempuri.org/")
        OrderAddRequest orderAddRequest,
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

    /**
     * 
     * @param orgId
     * @param unixExpireTimestamp
     * @param beginTime
     * @param endTime
     * @param signature
     * @return
     *     returns com.rose.mps.domain.order.publicservice.InvokeResultArrayOfPromotionPolicyResponse
     */
    @WebMethod(operationName = "GetPromotionRemains", action = "http://tempuri.org/IOrderService/GetPromotionRemains")
    @WebResult(name = "GetPromotionRemainsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPromotionRemains", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPromotionRemains")
    @ResponseWrapper(localName = "GetPromotionRemainsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPromotionRemainsResponse")
    public InvokeResultArrayOfPromotionPolicyResponse getPromotionRemains(
        @WebParam(name = "orgId", targetNamespace = "http://tempuri.org/")
        Long orgId,
        @WebParam(name = "beginTime", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar beginTime,
        @WebParam(name = "endTime", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar endTime,
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

    /**
     * 
     * @param unixExpireTimestamp
     * @param signature
     * @param checkinRequest
     * @return
     *     returns com.rose.mps.domain.order.publicservice.InvokeResultBoolean
     */
    @WebMethod(operationName = "AddCheckin", action = "http://tempuri.org/IOrderService/AddCheckin")
    @WebResult(name = "AddCheckinResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddCheckin", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddCheckin")
    @ResponseWrapper(localName = "AddCheckinResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddCheckinResponse")
    public InvokeResultBoolean addCheckin(
        @WebParam(name = "checkinRequest", targetNamespace = "http://tempuri.org/")
        CheckinRequest checkinRequest,
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

    /**
     * 
     * @param roomNumber
     * @param unixExpireTimestamp
     * @param hotelId
     * @param signature
     * @param orderId
     * @return
     *     returns com.rose.mps.domain.order.publicservice.InvokeResultBoolean
     */
    @WebMethod(operationName = "SetOrderRoom", action = "http://tempuri.org/IOrderService/SetOrderRoom")
    @WebResult(name = "SetOrderRoomResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SetOrderRoom", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetOrderRoom")
    @ResponseWrapper(localName = "SetOrderRoomResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetOrderRoomResponse")
    public InvokeResultBoolean setOrderRoom(
        @WebParam(name = "orderId", targetNamespace = "http://tempuri.org/")
        Long orderId,
        @WebParam(name = "hotelId", targetNamespace = "http://tempuri.org/")
        Long hotelId,
        @WebParam(name = "roomNumber", targetNamespace = "http://tempuri.org/")
        String roomNumber,
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

    /**
     * 
     * @param unixExpireTimestamp
     * @param occupationSearchRequest
     * @param signature
     * @return
     *     returns com.rose.mps.domain.order.publicservice.InvokeResultArrayOfOccupationResponse
     */
    @WebMethod(operationName = "SearchOccupation", action = "http://tempuri.org/IOrderService/SearchOccupation")
    @WebResult(name = "SearchOccupationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SearchOccupation", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchOccupation")
    @ResponseWrapper(localName = "SearchOccupationResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchOccupationResponse")
    public InvokeResultArrayOfOccupationResponse searchOccupation(
        @WebParam(name = "occupationSearchRequest", targetNamespace = "http://tempuri.org/")
        OccupationSearchRequest occupationSearchRequest,
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

    /**
     * 
     * @param checkinSearchRequest
     * @param unixExpireTimestamp
     * @param signature
     * @return
     *     returns com.rose.mps.domain.order.publicservice.InvokeResultArrayOfCheckinResponse
     */
    @WebMethod(operationName = "SearchCheckin", action = "http://tempuri.org/IOrderService/SearchCheckin")
    @WebResult(name = "SearchCheckinResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SearchCheckin", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchCheckin")
    @ResponseWrapper(localName = "SearchCheckinResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchCheckinResponse")
    public InvokeResultArrayOfCheckinResponse searchCheckin(
        @WebParam(name = "checkinSearchRequest", targetNamespace = "http://tempuri.org/")
        CheckinSearchRequest checkinSearchRequest,
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

    /**
     * 
     * @param unixExpireTimestamp
     * @param checkinNetDoorRequest
     * @param signature
     * @return
     *     returns com.rose.mps.domain.order.publicservice.InvokeResultArrayOfCheckinNetDoorResponse
     */
    @WebMethod(operationName = "SearchCheckinNetDoor", action = "http://tempuri.org/IOrderService/SearchCheckinNetDoor")
    @WebResult(name = "SearchCheckinNetDoorResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SearchCheckinNetDoor", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchCheckinNetDoor")
    @ResponseWrapper(localName = "SearchCheckinNetDoorResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchCheckinNetDoorResponse")
    public InvokeResultArrayOfCheckinNetDoorResponse searchCheckinNetDoor(
        @WebParam(name = "checkinNetDoorRequest", targetNamespace = "http://tempuri.org/")
        CheckinNetDoorRequest checkinNetDoorRequest,
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

    /**
     * 
     * @param unixExpireTimestamp
     * @param checkinNetDoorOpenRequest
     * @param signature
     * @return
     *     returns com.rose.mps.domain.order.publicservice.InvokeResultBoolean
     */
    @WebMethod(operationName = "OpenCheckinNetDoor", action = "http://tempuri.org/IOrderService/OpenCheckinNetDoor")
    @WebResult(name = "OpenCheckinNetDoorResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "OpenCheckinNetDoor", targetNamespace = "http://tempuri.org/", className = "org.tempuri.OpenCheckinNetDoor")
    @ResponseWrapper(localName = "OpenCheckinNetDoorResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.OpenCheckinNetDoorResponse")
    public InvokeResultBoolean openCheckinNetDoor(
        @WebParam(name = "checkinNetDoorOpenRequest", targetNamespace = "http://tempuri.org/")
        CheckinNetDoorOpenRequest checkinNetDoorOpenRequest,
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

    /**
     * 
     * @param checkoutRequest
     * @param unixExpireTimestamp
     * @param signature
     * @return
     *     returns com.rose.mps.domain.order.publicservice.InvokeResultArrayOfCheckoutResponse
     */
    @WebMethod(operationName = "Checkout", action = "http://tempuri.org/IOrderService/Checkout")
    @WebResult(name = "CheckoutResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Checkout", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Checkout")
    @ResponseWrapper(localName = "CheckoutResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CheckoutResponse")
    public InvokeResultArrayOfCheckoutResponse checkout(
        @WebParam(name = "checkoutRequest", targetNamespace = "http://tempuri.org/")
        CheckoutRequest checkoutRequest,
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

    /**
     * 
     * @param checkinGuestRequest
     * @param unixExpireTimestamp
     * @param signature
     * @return
     *     returns com.rose.mps.domain.order.publicservice.InvokeResultArrayOfCheckinGuestResponse
     */
    @WebMethod(operationName = "GetCheckinGuest", action = "http://tempuri.org/IOrderService/GetCheckinGuest")
    @WebResult(name = "GetCheckinGuestResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCheckinGuest", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCheckinGuest")
    @ResponseWrapper(localName = "GetCheckinGuestResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCheckinGuestResponse")
    public InvokeResultArrayOfCheckinGuestResponse getCheckinGuest(
        @WebParam(name = "checkinGuestRequest", targetNamespace = "http://tempuri.org/")
        CheckinGuestRequest checkinGuestRequest,
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

    /**
     * 
     * @param changeStayRequest
     * @param unixExpireTimestamp
     * @param signature
     * @return
     *     returns com.rose.mps.domain.order.publicservice.InvokeResultCheckinResponse
     */
    @WebMethod(operationName = "ChangeStay", action = "http://tempuri.org/IOrderService/ChangeStay")
    @WebResult(name = "ChangeStayResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ChangeStay", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangeStay")
    @ResponseWrapper(localName = "ChangeStayResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangeStayResponse")
    public InvokeResultCheckinResponse changeStay(
        @WebParam(name = "changeStayRequest", targetNamespace = "http://tempuri.org/")
        ChangeStayRequest changeStayRequest,
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

    /**
     * 
     * @param unixExpireTimestamp
     * @param checkGuestIdCardRequest
     * @param signature
     * @return
     *     returns com.rose.mps.domain.order.publicservice.InvokeResultBoolean
     */
    @WebMethod(operationName = "CheckGuestIdCard", action = "http://tempuri.org/IOrderService/CheckGuestIdCard")
    @WebResult(name = "CheckGuestIdCardResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CheckGuestIdCard", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CheckGuestIdCard")
    @ResponseWrapper(localName = "CheckGuestIdCardResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CheckGuestIdCardResponse")
    public InvokeResultBoolean checkGuestIdCard(
        @WebParam(name = "checkGuestIdCardRequest", targetNamespace = "http://tempuri.org/")
        CheckGuestIdCardRequest checkGuestIdCardRequest,
        @WebParam(name = "unixExpireTimestamp", targetNamespace = "http://tempuri.org/")
        Long unixExpireTimestamp,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        String signature);

}
